config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
	as :user do
		get "signin" => 'devise/sessions#new'
		delete "signout" => 'devise/sessions#destroy'
		get 'signup' => 'devise/registrations#new'
	end
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact_us' => 'pages#contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

#see Active Admin documentation
	def authorized?(action, subject = nil)
		user && user.admin?
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
	belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :recoverable, and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

	has_many :tweets
	has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # before_action :set_idea, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])
  end

  # GET /ideas/new
  def new
    @idea = current_user.ideas.new
  end

  # GET /ideas/1/edit
  def edit
    @idea = current_user.ideas.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)
    if @idea.save
      redirect_to @idea, notice: 'Idea was successfully created'
    else
      render :new
    # respond_to do |format|
    #   if @idea.save
    #     format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
    #     format.json { render :show, status: :created, location: @idea }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    @idea = current_user.ideas.find(params[:id])
      if @idea.update(idea_params)
        redirect_to @idea, notice: 'Idea was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = current_user.ideas.find(params[:id])
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_idea
    #   @idea = Idea.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :content, :value, :effort)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  #from devise, require auth except for main list and detail
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/ideas/_form.html.erb
<%= form_for(idea) do |f| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

# should text_area be changed to text_field, or not due to data type
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, class: "form-control" %> 
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %> 
  </div>

  <div class="form-group">
    <%= f.label :value %>
    <%= f.number_field :value, class: "form-control" %> 
  </div>

  <div class="form-group">
    <%= f.label :effort %>
    <%= f.number_field :effort, class: "form-control" %>
  </div>

    <%= f.submit 'Submit', class: "btn btn-primary"%>

<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Value</th>
      <th>Effort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.content %></td>
        <td><%= idea.value %></td>
        <td><%= idea.effort %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<div class="container"

<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

</div>

app/views/ideas/show.html.erb
# <p id="notice"><%= notice %></p>

<div class="container">
	<p>
		<strong>User:</strong>
		<%= @idea.user %>
	</p>

	<p>
	  <strong>Title:</strong>
	  <%= @idea.title %>
	</p>

	<p>
	  <strong>Content:</strong>
	  <%= @idea.content %>
	</p>

	<p>
	  <strong>Value:</strong>
	  <%= @idea.value %>
	</p>

	<p>
	  <strong>Effort:</strong>
	  <%= @idea.effort %>
	</p>

	<% if @idea.user == current_user %>
		<%= link_to 'Edit', edit_idea_path(@idea) %> |
	<% end %>
		<%= link_to 'Back', ideas_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddnit</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <%= link_to "Reddnit", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contact_us_path, class: "nav-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path, class: "btn btn-primary" %></li>
            <li class="nav-item pull-md-right"><%= link_to "Log in", signin_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 Reddnit | Powered by <a href="http://rubyonrails.org">Rails</a></p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us &#x1F601;</h1>
        <p>This is the sample project for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

<!--
<h1>About us</h1>
<p>We're working on our project. &quot;We&quot;, being me and my chatbot.</p>
<p>For now, contact me via Slack, or GitHub.</p>
-->

app/views/pages/contact_us.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact Us</h1>
        <p>Post a story or comment</a>.</p>
    </div>
</div>



<!--
<h1>Contact Us</h1>
<p>Post a story or comment.</p>
-->

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="jumbotron jumbotron-home">
	<div class="container">
	       	<h1>TINDER backwards is (nearly) REDDIT.</h1>
	    	<p>As they say, "Two sides of the same coin still means currency". So, vote selfishly. Or vote selflessly. Either way it doesn't matter. You found the place to propose, weigh and swipe ideas.</p>
	       	<%= link_to "Welcome back »", "#", class: "btn btn-primary btn-lg" %>
	</div>
	</div>
<% else %>
	<div class="jumbotron jumbotron-home">
	    <div class="container">
	    	<h1>REDDIT backwards is (nearly) TINDER.</h1>
	    	<p>As we like to say, "Two sides of the same coin still equals currency." So, share your thoughts with others, and then vote selflessly. Or vote selfishly. Doesn't matter...either way you found the place to propose, weigh and swipe ideas.</p>
	       	<%= link_to "Real soon now »", "#", class: "btn btn-primary btn-lg" %> 
	    </div>
	</div>
	<div class="container">
	    <div class="row">
	        <div class="col-md-4">
	            <h2>Propose</h2>
	            <p>Those ideas storming your brain? Get them out of your head, far away from email and meetings, and into a place where we put them up for consideration and use.</p>
	            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
	        </div>
	        <div class="col-md-4">
	            <h2>Weigh</h2>
	            <p>Value vs. Effort. Return vs. Investment. If everything is a priority, nothing is. So, consider the best ideas, set the others aside, and let's figure out what comes next. </p>
	            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
	        </div>
	        <div class="col-md-4">
	            <h2>Swipe</h2>
	            <p>And by "swipe" we do mean, we need to seize the top ideas. Except there will be rewards for those who offer the best proposals that actually get completed.</p>
	            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
	        </div>
	    </div>
	</div>
 <% end %> 
<!--
<h1>If Everything Is A Priority, Nothing Is a Priority</h1>
<h2>Like Reddit, For Ideas and Initiatives</h2>
<p>Backlogs for brainstorms and ideation, loosely constructed using stories, upvoting and comments.</p>
<h2>Background</h2>
<p>Once a year, sometimes twice, we formally evaluate new ideas and opportunities to explore and potentially do -- related to both technology and marketing. But then new opportunities and ideas pop up all year long, and we tend to either ignore these <em>or</em> see them as highest-priority objects in that moment. This info is also locked in siloes of email, chat, ticketing and project management systems, where it either rots or clutters.</p>
<h2>Goals</h2>
<p>We need a better way to capture these ideas (which can also release them from our cognitive load), discuss them, and both vote and comment on them.</p>
<p>There's probably software and services that exist for this, but I'll say I need something to be highly customized, including how it's deployed. Plus some techniques used here might be applied elsewhere.</p>
-->

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

    <%= f.submit 'Submit', class: "btn btn-primary"%>

<% end %>

app/views/tweets/edit.html.erb
<div class="container">

	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>

</div>

app/views/tweets/index.html.erb
<div class="container">

  <h1>Tweets</h1>

  <table class="table">
    <thead>
      <tr>
        <th>User</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.user.email %></td>
          <td><%= tweet.content %></td>
          <td><%= link_to 'Show', tweet %></td>
          <% if tweet.user == current_user %>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% if user_signed_in? %>
  <%= link_to 'New Tweet', new_tweet_path %>
<% end %>

</div>

app/views/tweets/new.html.erb
<div class="container">

	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>

</div>

app/views/tweets/show.html.erb
<div class="container">
	<p>
	  <strong>User:</strong>
	  <%= @tweet.user %>
	</p>

	<p>
	  <strong>Content:</strong>
	  <%= @tweet.content %>
	</p>
	<% if @tweet.user == current_user %>
		<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
	<% end %>
		<%= link_to 'Back', tweets_path %>

</div>